#ifndef PACKETS_H
#define PACKETS_H
#define PKT_GAMESERVER_CHARSEL_SCREEN 0x01

enum CHAR_SELECTION_SCREEN
{
	CSS_VERSION_CHECK = 0x01,
	CSS_REQUEST_ALL_CHAR = 0x02,
	CSS_CREATE_CHAR = 0x03,
	CSS_SELECT_CHAR = 0x05,
	CSS_UNK = 0x07,
	CSS_DELETE_CHAR = 0xb2
};

#define PKT_GAMESERVER_MESSAGE 0x71
enum MESSAGE_TYPE
{
	MT_LOCAL = 0x01,
	MT_WHISPER = 0x02,
	MT_PARTY = 0x03,
	MT_CLAN = 0x04,
	MT_SHOUT = 0x05,
	MT_GM_ANNOUNCE = 0x06,
	MT_SLASH_COMMAND = 0x07,
	MT_PLAYER_NOTICE = 0x08,
	MT_FORCE_SHOUT_REQUEST = 0x0B,
	MT_FORCE_SHOUT = 0x0E,
	MT_UNIQUE_ITEM_DROP = 0x10,
	MT_VALOROUS = 0x11,//0x12 weird dark yellow/orange text
	MT_PLAYER_ANNOUNCE = 0x14, //This is the bar thing when you go divine
	MT_PLAYER_LOGIN_ANNOUNCE = 0x16,//High rank player.
};
#define PKT_GAMESERVER_UPDATE_CHARACTER_EXP 0x13
#define PKT_GAMESERVER_CHARACTER_UPDATE_CURHPCHI 0x16
#define PKT_GAMESERVER_REGION_CHANGE_USER 0x21
#define PKT_GAMESERVER_CHARACTER_MOVE 0x22
#define PKT_GAMESERVER_CHARACTER_TELEPORT 0x24
#define PKT_GAMESERVER_CHARACTER_UPDATE_REGION 0x27
#define PKT_GAMESERVER_ZONE_CHANGE 0x28
#define PKT_GAMESERVER_REGION_CHANGE_NPC 0x31
#define PKT_GAMESERVER_NPC_MOVE 0x33
#define PKT_GAMESERVER_MORPH_PLAYER 0x37
#define PKT_GAMESERVER_DEMORPH_PLAYER 0x38
#define PKT_GAMESERVER_REQUEST_ATTACK 0x41
#define PKT_GAMESERVER_REQUEST_CAST_SKILL 0x42
#define PKT_GAMESERVER_CHANGE_COMBAT_STATE 0x43
#define PKT_GAMESERVER_REQUEST_ATTACK_AOE 0x44
#define PKT_GAMESERVER_REQUEST_CAST_TIMED_SKILL 0x49//Monk skills generaly
#define PKT_GAMESERVER_WORLD_MAP_TELEPORTER 0x50
#define PKT_GAMESERVER_MODIFY_ITEM 0x54
#define PKT_GAMESERVER_ADD_ITEM_CONTINUOS 0x57
#define PKT_GAMESERVER_ITEM_STACK_CHANGE 0x58
#define PKT_GAMESERVER_MOVE_ADD_ITEM 0x59
#define PKT_GAMESERVER_BANK_MOVE_GOLD 0x63
#define PKT_GAMESERVER_ADD_ITEM_TO_GROUND 0x67
#define PKT_GAMESERVER_CHANGE_CLIENT_ZONE 0x73
#define PKT_GAMESERVER_SKILLBOOK_SKILL 0x81
#define PKT_GAMESERVER_MEDITATE 0x82
#define PKT_GAMESERVER_UPDATE_CHARACTER_KILLCOUNT 0xA2
#define PKT_GAMESERVER_UPDATE_ZONE 0xA6
#define PKT_GAMESERVER_ADD_STATPT 0xC4
#define PKT_GAMESERVER_TARGET 0xCF //SocketID after.
#define PKT_GAMESERVER_ATTACK_SKILL_FINISH 0xFE //FE 02 00 not sure.

#define PKT_GAMESERVER_LOADINGSCREENUNK1 0x62 //00 3 bytes
#define PKT_GAMESERVER_LOADINGSCREENUNK2 0x07 //03 00 00 00 00 01 00 9 bytes(01 faction?)
#define PKT_GAMESERVER_LOADINGSCREENUNK3 0x3D //2 bytes.

enum InventorySub
{
	MOVE_ITEM_PICKUP = 0x01,
	MOVE_ITEM_REMOVE = 0x02,
	MOVE_ITEM_EMPTY = 0x03,
	MOVE_USE_ITEM = 0x04,
	MOVE_ITEM_VISIBILITY = 0x05,
	MOVE_ITEM_ITEM_STACK = 0x06,
	MOVE_ITEM_ITEM = 0x07,
	MOVE_OPEN_GAMBLECHEST = 0x08,
	MOVE_ITEM_SPLIT = 0x09,
	MOVE_ITEM_OPEN_MULTI_ITEM = 0x10,//Craftmans sack for example, contains more than one item!
	MOVE_ITEM_SHOW = 0x11,
	//Hammer delete is the little hammer thing in inventory that deletes almost anything.(DESTROY)
	MOVE_ITEM_USE_POTION = 0x23,
	MOVE_HAMMER_DELETE = 0x30
};

#define PKT_GAMESERVER_REQUEST_UNK 0x18
#define PKT_GAMESERVER_REQUEST_UNK2 0x42
#define PKT_GAMESERVER_UPDATE_ITEMSLOT 0xAF

enum ObjectType
{
	OBJECT_BIND = 0,
	OBJECT_GATE = 1,
	OBJECT_GATE2 = 2,
	OBJECT_GATE_LEVER = 3,
	OBJECT_FLAG_LEVER = 4,
	OBJECT_WARP_GATE = 5,
	OBJECT_REMOVE_BIND = 7,
	OBJECT_ANVIL = 8,
	OBJECT_ARTIFACT = 9
};
#endif